/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import toold.Util;

/**
 *
 * @author u05521391142
 */
public class JDlgUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuario
     */
    public JDlgUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFmtDataNasc_nvb = new javax.swing.JFormattedTextField();
        jTxtCidade_nvb = new javax.swing.JTextField();
        jFmtCep_nvb = new javax.swing.JFormattedTextField();
        jTxtEmail_nvb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtEnd_nvb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtBairro_nvb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtRg_nvb = new javax.swing.JFormattedTextField();
        jTxtNome_nvb = new javax.swing.JTextField();
        jFmtCpf_nvb = new javax.swing.JFormattedTextField();
        jTxtApelido_nvb = new javax.swing.JTextField();
        jTxtId_nvb = new javax.swing.JTextField();
        jTxtTelefone_nvb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtIdade_nvb = new javax.swing.JTextField();
        jCboAtivo_nvb = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTxtSexo_nvb = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFmtSenha_nvb = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("RG");

        jLabel10.setText("Email");

        jTxtCidade_nvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidade_nvbActionPerformed(evt);
            }
        });

        jLabel11.setText("Endereço");

        jLabel12.setText("Bairro");

        jLabel13.setText("CEP");

        jLabel14.setText("CPF");

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido");

        jLabel4.setText("Telefone");

        jTxtId_nvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtId_nvbActionPerformed(evt);
            }
        });

        jLabel5.setText("Idade");

        jLabel16.setText("Senha");

        jCboAtivo_nvb.setText("Ativo");
        jCboAtivo_nvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboAtivo_nvbActionPerformed(evt);
            }
        });

        jLabel6.setText("Sexo");

        jTxtSexo_nvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSexo_nvbActionPerformed(evt);
            }
        });

        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Cidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jBtnPesquisar)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxtId_nvb)
                        .addComponent(jFmtDataNasc_nvb)
                        .addComponent(jTxtNome_nvb)
                        .addComponent(jLabel7)
                        .addComponent(jLabel11)
                        .addComponent(jTxtEnd_nvb)
                        .addComponent(jFmtSenha_nvb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtApelido_nvb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCidade_nvb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtBairro_nvb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addGap(187, 274, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtRg_nvb, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFmtCep_nvb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jTxtEmail_nvb)
                            .addComponent(jFmtCpf_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboAtivo_nvb)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTxtTelefone_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtIdade_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtSexo_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtId_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNome_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApelido_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSexo_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdade_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTelefone_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtDataNasc_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCidade_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmail_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtRg_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEnd_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtBairro_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCep_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCpf_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtSenha_nvb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboAtivo_nvb))
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnAlterar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCidade_nvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidade_nvbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidade_nvbActionPerformed

    private void jTxtId_nvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtId_nvbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtId_nvbActionPerformed

    private void jCboAtivo_nvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboAtivo_nvbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboAtivo_nvbActionPerformed

    private void jTxtSexo_nvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSexo_nvbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSexo_nvbActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true,jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb, jCboAtivo_nvb,jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb,jBtnCancelar,jBtnConfirmar);
        Util.habilitar(false,jBtnIncluir,jBtnAlterar, jBtnExcluir);
        Util.limp(jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb,jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb, jCboAtivo_nvb);
//        incluindo = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true,jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb, jCboAtivo_nvb,jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb,jBtnCancelar,jBtnConfirmar);
        Util.habilitar(false,jBtnIncluir,jBtnAlterar, jBtnExcluir);
        Util.limp(jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb,jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb, jCboAtivo_nvb);
     //   incluindo = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        //int resp =  JOptionPane.showConfirmDialog(null,  "deseja excluir?", "Pergunta", JOptionPane.YES_NO_OPTION);
        //if(resp == JOptionPane.YES_OPTION){
            //ClienteNvb clienteNvb = viewBean();
            //ClienteDAO clienteDAO = new ClienteDAO();
            //clienteDAO.delete(clienteNvb);
            //}else{
            //   JOptionPane.showMessageDialog(null, "exclusão cancelada");
            //  Util.habilitar(false,jTxtId,jTxtNome,jTxtApelido,jTxtIdade, jFmtDataNasc,
                //    jFmtCpf, jFmtRg, jTxtTelefone, jTxtCep, jTxtEmaiil, jPwfSenha,
                //  jTxtSexo, jChbAtivo,jBtnCancelar,jBtnConfirmar);
            // Util.habilitar(true,jBtnIncluir,jBtnAlterar, jBtnExcluir);
            //{

                //Util.limp(jTxtId, jTxtCep, jFmtCpf, jFmtDataNasc, jTxtTelefone,jTxtEmaiil,
                    //         jFmtRg,jTxtSexo,jTxtNome,jTxtApelido,jTxtIdade,jChbAtivo);
              //  if (Util.perg("Deseja Excluir?") == true) {
               //     usuariosDAO.delete(viewBean());
             //   }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.habilitar(false,jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb, jCboAtivo_nvb,jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb,jBtnCancelar,jBtnConfirmar);
        Util.habilitar(true,jBtnIncluir,jBtnAlterar, jBtnExcluir);
        Util.limp(jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb, jCboAtivo_nvb, jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb);
        Util.perg("Deseja cancelar o registro?");
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed

     //   if (incluindo == true) {
      //      usuariosDAO.insert(viewBean());
       // } else {
    //        usuariosDAO.update(viewBean());
       // }
        Util.habilitar(true,jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb, jCboAtivo_nvb,jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb, jBtnCancelar,jBtnConfirmar);
        Util.habilitar(false,jBtnIncluir,jBtnAlterar, jBtnExcluir);
        Util.limp(jTxtId_nvb,jTxtNome_nvb,jTxtApelido_nvb,jTxtIdade_nvb, jFmtDataNasc_nvb,
            jFmtCpf_nvb, jFmtRg_nvb, jTxtTelefone_nvb, jFmtCep_nvb, jTxtEmail_nvb, jFmtSenha_nvb,
            jTxtSexo_nvb, jCboAtivo_nvb, jTxtCidade_nvb, jTxtBairro_nvb,jTxtEnd_nvb);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
      //  JDlgUsuarios_pesquisar jDlgUsuarios_pesquisar = new JDlgUsuarios_pesquisar(null, true);
       // jDlgUsuarios_pesquisar.setTelaAnterior(this);
      //  jDlgUsuarios_pesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuario dialog = new JDlgUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JCheckBox jCboAtivo_nvb;
    private javax.swing.JFormattedTextField jFmtCep_nvb;
    private javax.swing.JFormattedTextField jFmtCpf_nvb;
    private javax.swing.JFormattedTextField jFmtDataNasc_nvb;
    private javax.swing.JFormattedTextField jFmtRg_nvb;
    private javax.swing.JFormattedTextField jFmtSenha_nvb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtApelido_nvb;
    private javax.swing.JTextField jTxtBairro_nvb;
    private javax.swing.JTextField jTxtCidade_nvb;
    private javax.swing.JTextField jTxtEmail_nvb;
    private javax.swing.JTextField jTxtEnd_nvb;
    private javax.swing.JTextField jTxtId_nvb;
    private javax.swing.JTextField jTxtIdade_nvb;
    private javax.swing.JTextField jTxtNome_nvb;
    private javax.swing.JTextField jTxtSexo_nvb;
    private javax.swing.JTextField jTxtTelefone_nvb;
    // End of variables declaration//GEN-END:variables
}
